{
 "title": "Hyperledger Fabric Monitoring",
 "description": "HLF Monitoring Dashboard.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dashboard", "label": "Dashboard", "query": "prometheus" },
   {
    "name": "channel",
    "label": "Channel",
    "query": {
     "query": "label_values(ledger_transaction_count{},channel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hyperledger Fabric Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fabric Version",
   "type": "stat",
   "description": "The active version of Fabric.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (version) (fabric_version{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ledger Block Height per channel",
   "type": "bargauge",
   "description": "Height of the chain in blocks. ",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (channel) (ledger_blockchain_height{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction error rate ",
   "type": "stat",
   "description": "consensus proposal failure rate",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(avg by (channel) ({__name__=~\"consensus_etcdraft_proposal_failures\"} )/avg by (channel) ({__name__=~\"consensus_etcdraft_normal_proposals_received|consensus_etcdraft_config_proposals_received\", } ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endorsment Proposal Successful",
   "type": "stat",
   "description": "The number of successful proposals. ",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endorser_successful_proposals{}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Endorsment Proposal Requests",
   "type": "stat",
   "description": "The number of proposals received.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "endorser_proposals_received{ }", "legendFormat": "{{container}}" }
   ]
  },
  {
   "title": "Ledger Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocks - $channel",
   "type": "timeseries",
   "description": "Blocks across nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ledger_blockchain_height{ channel=\"$channel\" }",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "StateDB Commit Time - $channel",
   "type": "timeseries",
   "description": "Time taken in seconds for committing block changes to state db.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ledger_statedb_commit_time_bucket{ channel=\"$channel\"}[5m])) by (le,service))",
     "legendFormat": "P95 - {{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ledger_statedb_commit_time_bucket{ channel=\"$channel\"}[5m])) by (le,service))",
     "legendFormat": "P99 - {{service}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ledger_statedb_commit_time_bucket{ channel=\"$channel\"}[5m])) by (le,service))",
     "legendFormat": "P50 - {{service}}"
    }
   ]
  },
  {
   "title": "Ledger Block Processing Time - $channel",
   "type": "timeseries",
   "description": "Time taken in seconds for ledger block processing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ledger_block_processing_time_bucket{channel=\"$channel\"}[5m])) by (le,service))",
     "legendFormat": "P95 - {{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ledger_block_processing_time_bucket{channel=\"$channel\"}[5m])) by (le,service))",
     "legendFormat": "P99 - {{service}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ledger_block_processing_time_bucket{channel=\"$channel\"}[5m])) by (le,service))",
     "legendFormat": "P50 - {{service}}"
    }
   ]
  },
  {
   "title": "Couch DB Processing Time",
   "type": "timeseries",
   "description": "Time taken in seconds for the function to complete request to CouchDB.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,  sum by (le,service) (rate(couchdb_processing_time_bucket{}[5m])))",
     "legendFormat": "P95 - {{service}}"
    },
    {
     "expr": "histogram_quantile(0.99,  sum by (le,service) (rate(couchdb_processing_time_bucket{}[5m])))",
     "legendFormat": "P99 - {{service}}"
    },
    {
     "expr": "histogram_quantile(0.50,  sum by (le,service) (rate(couchdb_processing_time_bucket{}[5m])))",
     "legendFormat": "P50 - {{service}}"
    }
   ]
  },
  {
   "title": "Orderer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Orderers",
   "type": "stat",
   "description": "Total orderers",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (consensus_etcdraft_cluster_size{channel=\"$channel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Blocks - $channel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container)(ledger_blockchain_height{channel=\"$channel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions on channel - $channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (chaincode) (ledger_transaction_count{ channel=\"$channel\" ,chaincode!=\"unknown\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leader Orderer - $channel",
   "type": "stat",
   "description": "Current Leader orderer",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_etcdraft_is_leader{channel=\"$channel\"} == 1",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Block commit time - $channel",
   "type": "timeseries",
   "description": "Time taken in seconds for committing the block to storage",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ledger_blockstorage_commit_time_bucket{ channel=\"$channel\"}[5m])) by (le,service))",
     "legendFormat": "P95 - {{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ledger_blockstorage_commit_time_bucket{ channel=\"$channel\"}[5m])) by (le,service))",
     "legendFormat": "P95 - {{service}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ledger_blockstorage_commit_time_bucket{ channel=\"$channel\"}[5m])) by (le,service))",
     "legendFormat": "P05 - {{service}}"
    }
   ]
  },
  {
   "title": "Chaincode Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Duration - $channel",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job, chaincode) (rate(chaincode_shim_request_duration_sum{channel=\"$channel\", chaincode!~\"_lifecycle.*|cscc|qscc\" , }[5m])) / sum by(job, chaincode) (rate(chaincode_shim_request_duration_count{channel=\"$channel\", chaincode!~\"_lifecycle.*|cscc|qscc\", }[5m]))",
     "legendFormat": "{{job}} {{chaincode}}"
    }
   ]
  },
  {
   "title": "Request Received - $channel",
   "type": "timeseries",
   "description": "The number of chaincode shim requests received.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(channel,type) (rate(chaincode_shim_requests_received{channel=\"$channel\",chaincode!~\"_lifecycle.*|cscc|qscc\", }[5m]))",
     "legendFormat": "{{job}} {{chaincode}}"
    }
   ]
  },
  {
   "title": "Requests Completed - $channel",
   "type": "timeseries",
   "description": "The number of chaincode shim requests completed.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (chaincode,job) (rate(chaincode_shim_requests_completed{chaincode!~\"_lifecycle.*|cscc|qscc\",channel=\"$channel\", }[5m]))",
     "legendFormat": "{{job}} {{chaincode}}"
    }
   ]
  }
 ]
}